import { StyleSheet } from "react-native";

export default styles = StyleSheet.create({
  FeedDev: {
    backgroundColor: "#fff",
    alignItems: "center",
  },
  feedListImage: {
    width: 120,
    height: 120,
    margin: 2,
  },
  feedTitle: {
    color: "#000",
    fontSize: 30,
    lineHeight: 40,
    fontFamily: "Chalkboard SE",
  },
  AddPostDev: {
    alignItems: "center",
    alignSelf: "stretch",
  },
  button: {
    width: 100,
    justifyContent: "center",
    backgroundColor: "transparent",
  },
  container: {
    flex: 1,
    backgroundColor: "#fff",
    alignItems: "center",
    justifyContent: "center",
  },

  image: {
    width: 300,
    height: 300,
    resizeMode: "contain",
  },
  sliderContainer: {
    height: 200,
    width: "90%",
    marginTop: 20,
    justifyContent: "center",
    alignSelf: "center",
    borderRadius: 8,
  },
  slide: {
    flex: 1,
    justifyContent: "center",
    backgroundColor: "transparent",
    borderRadius: 8,
  },
  sliderImage: {
    height: "100%",
    width: "100%",
    alignSelf: "center",
    borderRadius: 8,
  },
  addPostIcon: {
    backgroundColor: "white",
    borderColor: "white",
    borderWidth: 1,
    borderRadius: 60,
    width: 50,
    height: 50,
    justifyContent: "center",
    alignItems: "center",
    shadowColor: "#999",
    shadowOpacity: 40,
    marginBottom: 5,
    shadowOffset: {
      height: 1,
    },
  },
  addFirsttIcon: {
    backgroundColor: "white",
    borderColor: "white",
    borderWidth: 1,
    borderRadius: 60,
    width: 50,
    height: 50,
    justifyContent: "center",
    alignItems: "center",
    shadowColor: "#999",
    shadowOpacity: 40,
    marginTop: 90,
    marginLeft: 150,
    shadowOffset: {
      height: 1,
    },
  },
  iconDev: {
    // direction: "ltr",
    // alignItems: "flex-end",
    paddingHorizontal: 20,
  },

  description: {
    fontFamily: "Chalkboard SE",
    fontSize: 18,
    color: "#121212",
    height: 124,
    width: 272,
  },
  itemsContainer: {
    width: 410,
    height: 300,
  },
  itemsView: {
    width: 410,
    height: 85,
    justifyContent: "flex-end",
    alignItems: "stretch",
    marginTop: 47,
  },
  itemDiv: {
    width: 380,
    height: 72,
  },
  itemName: {
    fontFamily: "Chalkboard SE",
    fontSize: 20,
    color: "#121212",
    height: 23,
    width: 300,
    marginTop: -60,
    marginLeft: 21,
  },

  itemBrand: {
    fontFamily: "Chalkboard SE",
    fontSize: 20,
    color: "#121212",
    height: 20,
    width: 300,
    marginTop: 49,
    marginLeft: 21,
  },
  rect5: {
    marginTop: -40,
    backgroundColor: "white",
    borderColor: "white",
    borderWidth: 1,
    borderRadius: 60,
    width: 25,
    height: 25,
    justifyContent: "center",
    alignItems: "center",
    alignSelf: "flex-end",
    shadowColor: "#999",
    shadowOpacity: 40,
    marginBottom: 5,
    shadowOffset: {
      height: 1,
    },
  },
  itemPrice: {
    fontFamily: "Chalkboard SE",
    fontSize: 20,
    color: "#121212",
    height: 20,
    width: 300,
    marginLeft: 21,
  },
  doneDive: {
    width: 44,
    height: 44,
    marginTop: 17,
    marginLeft: 184,
  },
  cupertinoButtonDelete: {
    height: 44,
    width: 44,
  },
});
